# Generated by Django 2.1.4 on 2018-12-13 13:36

from django.db import migrations, models
import django.db.models.deletion
import find.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('home', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/non.png', upload_to=find.models.get_image_missings_path)),
            ],
        ),
        migrations.CreateModel(
            name='Missing_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('missing_time', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('missing_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Adress')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('found', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Post_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('telephone', models.CharField(max_length=12)),
                ('position', models.CharField(max_length=30)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Adress')),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.ImageField(default='images/non.png', upload_to=find.models.get_image_victims_path)),
                ('additional_information', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Adress')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Post_type'),
        ),
        migrations.AddField(
            model_name='missing_person',
            name='relatives',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Relative'),
        ),
        migrations.AddField(
            model_name='images',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Missing_person'),
        ),
    ]
