# Generated by Django 2.1.4 on 2018-12-18 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('find', '0002_auto_20181218_0145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='person',
            new_name='person_id',
        ),
        migrations.RemoveField(
            model_name='missing_person',
            name='relatives',
        ),
        migrations.RemoveField(
            model_name='post',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.AddField(
            model_name='post',
            name='missing_person_id',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='find.Missing_person'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type_id',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='find.Post_type'),
        ),
        migrations.AddField(
            model_name='post',
            name='relative_id',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='find.Relative'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='victim_id',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='find.Victim'),
        ),
        migrations.AddField(
            model_name='relative',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='missing_person',
            name='missing_place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='missing_person',
            name='nickname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='relative',
            name='adress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='additional_information',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='place',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
