# Generated by Django 2.1.4 on 2018-12-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0003_auto_20181218_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missing_person',
            old_name='fullname',
            new_name='name',
        ),
    ]
