# Generated by Django 2.1.4 on 2018-12-18 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0004_auto_20181218_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 18, 31, 28, 411513)),
        ),
    ]
