# Generated by Django 2.1.4 on 2018-12-18 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0005_auto_20181218_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='found',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 18, 56, 44, 871661)),
        ),
    ]
